[class.bard]
name = "Bard"
hit_die = "d8"
armor_proficiencies = ["Light Armor"]
weapon_proficiencies = ["Simple Weapons", "Hand Crossbow", "Longsword", "Rapier", "Shortsword"]

[class.bard.choices.subclass]
required = true
type = "class"
options = ["college_of_lore"]

[class.bard.choices.musical_instrument_1]
required = true
type = "equipment"
options = ["bagpipes", "drum", "dulcimer", "flute", "lute", "lyre", "horn", "pan_flute", "shawm", "viol"]

[class.bard.choices.musical_instrument_2]
required = true
type = "equipment"
options = ["bagpipes", "drum", "dulcimer", "flute", "lute", "lyre", "horn", "pan_flute", "shawm", "viol"]

[class.bard.choices.musical_instrument_3]
required = true
type = "equipment"
options = ["bagpipes", "drum", "dulcimer", "flute", "lute", "lyre", "horn", "pan_flute", "shawm", "viol"]

[class.bard.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "acrobatics",
  "animal_handling",
  "arcana",
  "athletics",
  "deception",
  "history",
  "insight",
  "intimidation",
  "investigation",
  "medicine",
  "nature",
  "perception",
  "performance",
  "persuasion",
  "religion",
  "sleight_of_hand",
  "stealth",
  "survival",
]

[class.bard.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "acrobatics",
  "animal_handling",
  "arcana",
  "athletics",
  "deception",
  "history",
  "insight",
  "intimidation",
  "investigation",
  "medicine",
  "nature",
  "perception",
  "performance",
  "persuasion",
  "religion",
  "sleight_of_hand",
  "stealth",
  "survival",
]

[class.bard.choices.skill_proficiency_3]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "acrobatics",
  "animal_handling",
  "arcana",
  "athletics",
  "deception",
  "history",
  "insight",
  "intimidation",
  "investigation",
  "medicine",
  "nature",
  "perception",
  "performance",
  "persuasion",
  "religion",
  "sleight_of_hand",
  "stealth",
  "survival",
]

[[class.bard.contributes]]
target = "saving_throw('dexterity').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.bard.contributes]]
target = "saving_throw('charisma').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.bard.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 8"

[[class.bard.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.bard.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('charisma').modifier"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_1"
value = "character_trait('full_caster_slots').level_1"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_2"
value = "character_trait('full_caster_slots').level_2"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_3"
value = "character_trait('full_caster_slots').level_3"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_4"
value = "character_trait('full_caster_slots').level_4"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_5"
value = "character_trait('full_caster_slots').level_5"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_6"
value = "character_trait('full_caster_slots').level_6"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_7"
value = "character_trait('full_caster_slots').level_7"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_8"
value = "character_trait('full_caster_slots').level_8"

[[class.bard.contributes]]
target = "character_trait('spell_slots').level_9"
value = "character_trait('full_caster_slots').level_9"

[[class.bard.contributes]]
target = "character_trait('cantrips_known').count"
value = "class('bard').cantrips_known_count"

[[class.bard.contributes]]
target = "character_trait('spells_known').count"
value = "class('bard').spells_known_count"

[[class.bard.contributes]]
target = "character_trait('max_spell_level').level"
value = "class('bard').max_spell_level"

[class.bard.cantrips_known_count]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 2], [4, 3], [10, 4]]

[class.bard.spells_known_count]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 4], [2, 5], [3, 6], [4, 7], [5, 8], [6, 9], [7, 10], [8, 11], [9, 12], [10, 14], [11, 15], [13, 16], [14, 18], [15, 19], [17, 20], [18, 22]]

[class.bard.max_spell_level]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 1], [3, 2], [5, 3], [7, 4], [9, 5], [11, 6], [13, 7], [15, 8], [17, 9]]

[class.college_of_lore]
name = "College of Lore"
