[class.cleric]
name = "Cleric"
hit_die = "d8"
armor_proficiencies = ["Light Armor", "Medium Armor", "Shield"]
weapon_proficiencies = ["Simple Weapons"]

[class.cleric.choices.subclass]
required = true
type = "class"
options = ["life_domain"]

[class.cleric.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["history", "insight", "medicine", "persuasion", "religion"]

[class.cleric.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["history", "insight", "medicine", "persuasion", "religion"]

[[class.cleric.contributes]]
target = "saving_throw('wisdom').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.cleric.contributes]]
target = "saving_throw('charisma').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.cleric.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 8"

[[class.cleric.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.cleric.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('wisdom').modifier"

[class.life_domain]
name = "Life Domain"
armor_proficiencies = ["Heavy Armor"]
