[class.druid]
name = "Druid"
hit_die = "d8"
armor_proficiencies = ["Light Armor", "Medium Armor", "Shield"]
weapon_proficiencies = ["Club", "Dagger", "Dart", "Javelin", "Mace", "Quarterstaff", "Scimitar", "Sickle", "Sling", "Spear"]
tool_proficiencies = ["Herbalism Kit"]

asi_slots.type = "mapping"
asi_slots.input = "character_trait('character_level').level"
asi_slots.steps = [[1, 0], [4, 1], [8, 2], [12, 3], [16, 4], [19, 5]]
[class.druid.choices.subclass]
required = true
type = "class"
options = ["circle_of_the_land"]

[class.druid.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "arcana",
  "animal_handling",
  "insight",
  "medicine",
  "nature",
  "perception",
  "religion",
  "survival",
]

[class.druid.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "arcana",
  "animal_handling",
  "insight",
  "medicine",
  "nature",
  "perception",
  "religion",
  "survival",
]

[[class.druid.contributes]]
target = "saving_throw('intelligence').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.druid.contributes]]
target = "saving_throw('wisdom').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.druid.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 8"

[[class.druid.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.druid.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('wisdom').modifier"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_1"
value = "character_trait('full_caster_slots').level_1"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_2"
value = "character_trait('full_caster_slots').level_2"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_3"
value = "character_trait('full_caster_slots').level_3"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_4"
value = "character_trait('full_caster_slots').level_4"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_5"
value = "character_trait('full_caster_slots').level_5"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_6"
value = "character_trait('full_caster_slots').level_6"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_7"
value = "character_trait('full_caster_slots').level_7"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_8"
value = "character_trait('full_caster_slots').level_8"

[[class.druid.contributes]]
target = "character_trait('spell_slots').level_9"
value = "character_trait('full_caster_slots').level_9"

[[class.druid.contributes]]
target = "character_trait('cantrips_known').count"
value = "class('druid').cantrips_known_count"

[[class.druid.contributes]]
target = "character_trait('max_spell_level').level"
value = "class('druid').max_spell_level"

[class.druid.cantrips_known_count]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 2], [4, 3], [10, 4]]

[class.druid.max_spell_level]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 1], [3, 2], [5, 3], [7, 4], [9, 5], [11, 6], [13, 7], [15, 8], [17, 9]]

[[class.druid.contributes]]
target = "character_trait('asi_count').count"
value = "class('druid').asi_slots"

[class.circle_of_the_land]
name = "Circle of the Land"
