[class.paladin]
name = "Paladin"
hit_die = "d10"
armor_proficiencies = ["Light Armor", "Medium Armor", "Heavy Armor", "Shield"]
weapon_proficiencies = ["Simple Weapons", "Martial Weapons"]

asi_slots.type = "mapping"
asi_slots.input = "character_trait('character_level').level"
asi_slots.steps = [[1, 0], [4, 1], [8, 2], [12, 3], [16, 4], [19, 5]]
[class.paladin.choices.subclass]
required = true
type = "class"
options = ["oath_of_devotion"]

[class.paladin.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"]

[class.paladin.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"]

[[class.paladin.contributes]]
target = "saving_throw('wisdom').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.paladin.contributes]]
target = "saving_throw('charisma').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.paladin.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 10"

[[class.paladin.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.paladin.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('charisma').modifier"

[[class.paladin.contributes]]
target = "character_trait('spell_slots').level_1"
value = "character_trait('half_caster_slots').level_1"

[[class.paladin.contributes]]
target = "character_trait('spell_slots').level_2"
value = "character_trait('half_caster_slots').level_2"

[[class.paladin.contributes]]
target = "character_trait('spell_slots').level_3"
value = "character_trait('half_caster_slots').level_3"

[[class.paladin.contributes]]
target = "character_trait('spell_slots').level_4"
value = "character_trait('half_caster_slots').level_4"

[[class.paladin.contributes]]
target = "character_trait('spell_slots').level_5"
value = "character_trait('half_caster_slots').level_5"

[[class.paladin.contributes]]
target = "character_trait('max_spell_level').level"
value = "class('paladin').max_spell_level"

[class.paladin.max_spell_level]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 0], [2, 1], [5, 2], [9, 3], [13, 4], [17, 5]]

[[class.paladin.contributes]]
target = "character_trait('asi_count').count"
value = "class('paladin').asi_slots"

[class.oath_of_devotion]
name = "Oath of Devotion"
