[class.ranger]
name = "Ranger"
hit_die = "d10"
armor_proficiencies = ["Light Armor", "Medium Armor", "Shield"]
weapon_proficiencies = ["Simple Weapons", "Martial Weapons"]

[class.ranger.choices.subclass]
required = true
type = "class"
options = ["hunter"]

[class.ranger.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "animal_handling",
  "athletics",
  "insight",
  "investigation",
  "nature",
  "perception",
  "stealth",
  "survival",
]

[class.ranger.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "animal_handling",
  "athletics",
  "insight",
  "investigation",
  "nature",
  "perception",
  "stealth",
  "survival",
]

[class.ranger.choices.skill_proficiency_3]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "animal_handling",
  "athletics",
  "insight",
  "investigation",
  "nature",
  "perception",
  "stealth",
  "survival",
]

[[class.ranger.contributes]]
target = "saving_throw('strength').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.ranger.contributes]]
target = "saving_throw('dexterity').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.ranger.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 10"

[[class.ranger.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.ranger.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('wisdom').modifier"

[class.hunter]
name = "Hunter"
