[class.ranger]
name = "Ranger"
hit_die = "d10"
armor_proficiencies = ["Light Armor", "Medium Armor", "Shield"]
weapon_proficiencies = ["Simple Weapons", "Martial Weapons"]

[class.ranger.choices.subclass]
required = true
type = "class"
options = ["hunter"]

[class.ranger.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "animal_handling",
  "athletics",
  "insight",
  "investigation",
  "nature",
  "perception",
  "stealth",
  "survival",
]

[class.ranger.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "animal_handling",
  "athletics",
  "insight",
  "investigation",
  "nature",
  "perception",
  "stealth",
  "survival",
]

[class.ranger.choices.skill_proficiency_3]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = [
  "animal_handling",
  "athletics",
  "insight",
  "investigation",
  "nature",
  "perception",
  "stealth",
  "survival",
]

[[class.ranger.contributes]]
target = "saving_throw('strength').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.ranger.contributes]]
target = "saving_throw('dexterity').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.ranger.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 10"

[[class.ranger.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.ranger.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('wisdom').modifier"

[[class.ranger.contributes]]
target = "character_trait('spell_slots').level_1"
value = "character_trait('half_caster_slots').level_1"

[[class.ranger.contributes]]
target = "character_trait('spell_slots').level_2"
value = "character_trait('half_caster_slots').level_2"

[[class.ranger.contributes]]
target = "character_trait('spell_slots').level_3"
value = "character_trait('half_caster_slots').level_3"

[[class.ranger.contributes]]
target = "character_trait('spell_slots').level_4"
value = "character_trait('half_caster_slots').level_4"

[[class.ranger.contributes]]
target = "character_trait('spell_slots').level_5"
value = "character_trait('half_caster_slots').level_5"

[[class.ranger.contributes]]
target = "character_trait('spells_known').count"
value = "class('ranger').spells_known_count"

[[class.ranger.contributes]]
target = "character_trait('max_spell_level').level"
value = "class('ranger').max_spell_level"

[class.ranger.spells_known_count]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 0], [2, 2], [3, 3], [5, 4], [7, 5], [9, 6], [11, 7], [13, 8], [15, 9], [17, 10], [19, 11]]

[class.ranger.max_spell_level]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 0], [2, 1], [5, 2], [9, 3], [13, 4], [17, 5]]

[class.hunter]
name = "Hunter"
