[class.sorcerer]
name = "Sorcerer"
hit_die = "d6"
weapon_proficiencies = ["Dagger", "Dart", "Sling", "Quarterstaff", "Light Crossbow"]

[class.sorcerer.choices.subclass]
required = true
type = "class"
options = ["draconic_bloodline"]

[class.sorcerer.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"]

[class.sorcerer.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"]

[[class.sorcerer.contributes]]
target = "saving_throw('constitution').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.sorcerer.contributes]]
target = "saving_throw('charisma').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.sorcerer.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 6"

[[class.sorcerer.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.sorcerer.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('charisma').modifier"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_1"
value = "character_trait('full_caster_slots').level_1"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_2"
value = "character_trait('full_caster_slots').level_2"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_3"
value = "character_trait('full_caster_slots').level_3"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_4"
value = "character_trait('full_caster_slots').level_4"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_5"
value = "character_trait('full_caster_slots').level_5"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_6"
value = "character_trait('full_caster_slots').level_6"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_7"
value = "character_trait('full_caster_slots').level_7"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_8"
value = "character_trait('full_caster_slots').level_8"

[[class.sorcerer.contributes]]
target = "character_trait('spell_slots').level_9"
value = "character_trait('full_caster_slots').level_9"

[class.draconic_bloodline]
name = "Draconic Bloodline"
