[class.wizard]
name = "Wizard"
hit_die = "d6"
weapon_proficiencies = ["Dagger", "Dart", "Sling", "Quarterstaff", "Light Crossbow"]

asi_slots.type = "mapping"
asi_slots.input = "character_trait('character_level').level"
asi_slots.steps = [[1, 0], [4, 1], [8, 2], [12, 3], [16, 4], [19, 5]]
[class.wizard.choices.subclass]
required = true
type = "class"
options = ["school_of_evocation"]

[class.wizard.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["arcana", "history", "insight", "investigation", "medicine", "religion"]

[class.wizard.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["arcana", "history", "insight", "investigation", "medicine", "religion"]

[[class.wizard.contributes]]
target = "saving_throw('intelligence').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.wizard.contributes]]
target = "saving_throw('wisdom').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.wizard.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 6"

[[class.wizard.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.wizard.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('intelligence').modifier"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_1"
value = "character_trait('full_caster_slots').level_1"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_2"
value = "character_trait('full_caster_slots').level_2"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_3"
value = "character_trait('full_caster_slots').level_3"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_4"
value = "character_trait('full_caster_slots').level_4"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_5"
value = "character_trait('full_caster_slots').level_5"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_6"
value = "character_trait('full_caster_slots').level_6"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_7"
value = "character_trait('full_caster_slots').level_7"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_8"
value = "character_trait('full_caster_slots').level_8"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_9"
value = "character_trait('full_caster_slots').level_9"

[[class.wizard.contributes]]
target = "character_trait('spells_known').count"
value = "class('wizard').spells_known_count"

[[class.wizard.contributes]]
target = "character_trait('cantrips_known').count"
value = "class('wizard').cantrips_known_count"

[[class.wizard.contributes]]
target = "character_trait('max_spell_level').level"
value = "class('wizard').max_spell_level"

[class.wizard.spells_known_count]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 6], [2, 8], [3, 10], [4, 12], [5, 14], [6, 16], [7, 18], [8, 20], [9, 22], [10, 24], [11, 26], [12, 28], [13, 30], [14, 32], [15, 34], [16, 36], [17, 38], [18, 40], [19, 42], [20, 44]]

[class.wizard.cantrips_known_count]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 3], [4, 4], [10, 5]]

[class.wizard.max_spell_level]
type = "mapping"
input = "character_trait('character_level').level"
steps = [[1, 1], [3, 2], [5, 3], [7, 4], [9, 5], [11, 6], [13, 7], [15, 8], [17, 9]]

[[class.wizard.contributes]]
target = "character_trait('asi_count').count"
value = "class('wizard').asi_slots"

[class.school_of_evocation]
name = "School of Evocation"
