[class.wizard]
name = "Wizard"
hit_die = "d6"
weapon_proficiencies = ["Dagger", "Dart", "Sling", "Quarterstaff", "Light Crossbow"]

[class.wizard.choices.subclass]
required = true
type = "class"
options = ["school_of_evocation"]

[class.wizard.choices.skill_proficiency_1]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["arcana", "history", "insight", "investigation", "medicine", "religion"]

[class.wizard.choices.skill_proficiency_2]
required = true
type = "skill"
contributes_field = "modifier"
contributes_value = "character_trait('proficiency_bonus').bonus"
options = ["arcana", "history", "insight", "investigation", "medicine", "religion"]

[[class.wizard.contributes]]
target = "saving_throw('intelligence').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.wizard.contributes]]
target = "saving_throw('wisdom').modifier"
value = "character_trait('proficiency_bonus').bonus"

[[class.wizard.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier + 6"

[[class.wizard.contributes]]
target = "character_trait('max_hit_points').points"
value = "ability('constitution').modifier * (character_trait('character_level').level - 1)"

[[class.wizard.contributes]]
target = "character_trait('spellcasting_ability_modifier').value"
value = "ability('intelligence').modifier"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_1"
value = "character_trait('full_caster_slots').level_1"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_2"
value = "character_trait('full_caster_slots').level_2"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_3"
value = "character_trait('full_caster_slots').level_3"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_4"
value = "character_trait('full_caster_slots').level_4"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_5"
value = "character_trait('full_caster_slots').level_5"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_6"
value = "character_trait('full_caster_slots').level_6"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_7"
value = "character_trait('full_caster_slots').level_7"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_8"
value = "character_trait('full_caster_slots').level_8"

[[class.wizard.contributes]]
target = "character_trait('spell_slots').level_9"
value = "character_trait('full_caster_slots').level_9"

[class.school_of_evocation]
name = "School of Evocation"
