[race.elf]
name = "Elf"
languages = ["common", "elvish"]

[race.elf.choices.subrace]
required = true
type = "race"
options = ["high_elf"]

[[race.elf.contributes]]
target = "character_trait('speed').amount"
value = 30

[[race.elf.contributes]]
target = "character_trait('darkvision').range"
value = 60

[[race.elf.contributes]]
target = "ability('dexterity').total_score"
value = 2

[race.high_elf]
name = "High Elf"
weapon_proficiencies = ["Longsword", "Shortsword", "Shortbow", "Longbow"]

[race.high_elf.choices.extra_language]
required = true
type = "language"
options = [
  "dwarvish",
  "giant",
  "gnomish",
  "goblin",
  "halfling",
  "orc",
  "abyssal",
  "celestial",
  "draconic",
  "deep_speech",
  "infernal",
  "primordial",
  "sylvan",
  "undercommon",
]

[[race.high_elf.contributes]]
target = "ability('intelligence').total_score"
value = 1
