[race.gnome]
name = "Gnome"
languages = ["common", "gnomish"]

[race.gnome.choices.subrace]
required = true
type = "race"
options = ["rock_gnome"]

[[race.gnome.contributes]]
target = "character_trait('speed').amount"
value = 25

[[race.gnome.contributes]]
target = "character_trait('darkvision').range"
value = 60

[[race.gnome.contributes]]
target = "ability('intelligence').total_score"
value = 2

[race.rock_gnome]
name = "Rock Gnome"
tool_proficiencies = ["tinkers_tools"]

[[race.rock_gnome.contributes]]
target = "ability('constitution').total_score"
value = 1
