[race.halfling]
name = "Halfling"
languages = ["common", "halfling"]

[race.halfling.choices.subrace]
required = true
type = "race"
options = ["lightfoot_halfling", "stout_halfling"]

[[race.halfling.contributes]]
target = "character_trait('speed').feet"
value = 25

[[race.halfling.contributes]]
target = "ability('dexterity').total_score"
value = 2

[race.lightfoot_halfling]
name = "Lightfoot Halfling"

[[race.lightfoot_halfling.contributes]]
target = "ability('charisma').total_score"
value = 1

[race.stout_halfling]
name = "Stout Halfling"

[[race.stout_halfling.contributes]]
target = "ability('constitution').total_score"
value = 1
