[race.half_elf]
name = "Half-Elf"
languages = ["common", "elvish"]

[race.half_elf.choices.extra_language]
required = true
type = "language"
options = [
  "dwarvish",
  "giant",
  "gnomish",
  "goblin",
  "halfling",
  "orc",
  "abyssal",
  "celestial",
  "draconic",
  "deep_speech",
  "infernal",
  "primordial",
  "sylvan",
  "undercommon",
]

[[race.half_elf.contributes]]
target = "character_trait('speed').feet"
value = 30

[[race.half_elf.contributes]]
target = "character_trait('darkvision').range"
value = 60

[[race.half_elf.contributes]]
target = "ability('charisma').total_score"
value = 2
