[race.human]
name = "Human"
languages = ["common"]

[race.human.choices.extra_language]
required = true
type = "language"
options = [
  "dwarvish",
  "elvish",
  "giant",
  "gnomish",
  "goblin",
  "halfling",
  "orc",
  "abyssal",
  "celestial",
  "draconic",
  "deep_speech",
  "infernal",
  "primordial",
  "sylvan",
  "undercommon",
]

[[race.human.contributes]]
target = "ability('strength').total_score"
value = 1

[[race.human.contributes]]
target = "ability('dexterity').total_score"
value = 1

[[race.human.contributes]]
target = "ability('constitution').total_score"
value = 1

[[race.human.contributes]]
target = "ability('wisdom').total_score"
value = 1

[[race.human.contributes]]
target = "ability('intelligence').total_score"
value = 1

[[race.human.contributes]]
target = "ability('charisma').total_score"
value = 1
