[race.human]
name = "Human"

[[race.human.contributes]]
target = "ability('strength').total_score"
value = 1

[[race.human.contributes]]
target = "ability('dexterity').total_score"
value = 1

[[race.human.contributes]]
target = "ability('constitution').total_score"
value = 1

[[race.human.contributes]]
target = "ability('wisdom').total_score"
value = 1

[[race.human.contributes]]
target = "ability('intelligence').total_score"
value = 1

[[race.human.contributes]]
target = "ability('charisma').total_score"
value = 1

[race.dragonborn]
name = "Dragonborn"

[[race.dragonborn.contributes]]
target = "ability('strength').total_score"
value = 2

[[race.dragonborn.contributes]]
target = "ability('charisma').total_score"
value = 1

[race.half_elf]
name = "Half-Elf"

[[race.half_elf.contributes]]
target = "ability('charisma').total_score"
value = 2

[race.half_orc]
name = "Half-Orc"

[[race.half_orc.contributes]]
target = "ability('strength').total_score"
value = 2

[[race.half_orc.contributes]]
target = "ability('constitution').total_score"
value = 1

[race.tiefling]
name = "Tiefling"

[[race.tiefling.contributes]]
target = "ability('intelligence').total_score"
value = 1

[[race.tiefling.contributes]]
target = "ability('charisma').total_score"
value = 2

[race.dwarf]
name = "Dwarf"

[race.dwarf.choices.subrace]
required = true
type = "race"
options = ["hill_dwarf", "mountain_dwarf"]

[[race.dwarf.contributes]]
target = "ability('constitution').total_score"
value = 2

[race.hill_dwarf]
name = "Hill Dwarf"

[[race.hill_dwarf.contributes]]
target = "ability('wisdom').total_score"
value = 1

[race.mountain_dwarf]
name = "Mountain Dwarf"

[[race.mountain_dwarf.contributes]]
target = "ability('strength').total_score"
value = 2

[race.elf]
name = "Elf"

[race.elf.choices.subrace]
required = true
type = "race"
options = ["high_elf", "wood_elf", "dark_elf"]

[[race.elf.contributes]]
target = "ability('dexterity').total_score"
value = 2

[race.high_elf]
name = "High Elf"

[[race.high_elf.contributes]]
target = "ability('intelligence').total_score"
value = 1

[race.wood_elf]
name = "Wood Elf"

[[race.wood_elf.contributes]]
target = "ability('wisdom').total_score"
value = 1

[race.dark_elf]
name = "Dark Elf"

[[race.dark_elf.contributes]]
target = "ability('charisma').total_score"
value = 1

[race.halfling]
name = "Halfling"

[race.halfling.choices.subrace]
required = true
type = "race"
options = ["lightfoot_halfling", "stout_halfling"]

[[race.halfling.contributes]]
target = "ability('dexterity').total_score"
value = 2

[race.lightfoot_halfling]
name = "Lightfoot Halfling"

[[race.lightfoot_halfling.contributes]]
target = "ability('charisma').total_score"
value = 1

[race.stout_halfling]
name = "Stout Halfling"

[[race.stout_halfling.contributes]]
target = "ability('constitution').total_score"
value = 1

[race.gnome]
name = "Gnome"

[race.gnome.choices.subrace]
required = true
type = "race"
options = ["forest_gnome", "rock_gnome"]

[[race.gnome.contributes]]
target = "ability('intelligence').total_score"
value = 2

[race.forest_gnome]
name = "Forest Gnome"

[[race.forest_gnome.contributes]]
target = "ability('dexterity').total_score"
value = 1

[race.rock_gnome]
name = "Rock Gnome"

[[race.rock_gnome.contributes]]
target = "ability('constitution').total_score"
value = 1
