[race.tiefling]
name = "Tiefling"
languages = ["common", "infernal"]

[[race.tiefling.contributes]]
target = "character_trait('speed').feet"
value = 30

[[race.tiefling.contributes]]
target = "character_trait('darkvision').range"
value = 60

[[race.tiefling.contributes]]
target = "ability('intelligence').total_score"
value = 1

[[race.tiefling.contributes]]
target = "ability('charisma').total_score"
value = 2
