# Simple Melee Weapons

[equipment.club]
name = "Club"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 1
cost.currency = "sp"
damages = [{dice = "1d4", type = "bludgeoning"}]
weight = 2
properties = ["light"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('club').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.dagger]
name = "Dagger"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 2
cost.currency = "gp"
damages = [{dice = "1d4", type = "piercing"}]
weight = 1
properties = ["finesse", "light", "thrown"]
range_normal = 20
range_long = 60
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "max(ability('strength').modifier, ability('dexterity').modifier) + equipment('dagger').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.greatclub]
name = "Greatclub"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 2
cost.currency = "sp"
damages = [{dice = "1d8", type = "bludgeoning"}]
weight = 10
properties = ["two-handed"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('greatclub').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.handaxe]
name = "Handaxe"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 5
cost.currency = "gp"
damages = [{dice = "1d6", type = "slashing"}]
weight = 2
properties = ["light", "thrown"]
range_normal = 20
range_long = 60
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('handaxe').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.javelin]
name = "Javelin"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 5
cost.currency = "sp"
damages = [{dice = "1d6", type = "piercing"}]
weight = 2
properties = ["thrown"]
range_normal = 30
range_long = 120
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('javelin').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.light_hammer]
name = "Light Hammer"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 2
cost.currency = "gp"
damages = [{dice = "1d4", type = "bludgeoning"}]
weight = 2
properties = ["light", "thrown"]
range_normal = 20
range_long = 60
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('light_hammer').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.mace]
name = "Mace"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 5
cost.currency = "gp"
damages = [{dice = "1d6", type = "bludgeoning"}]
weight = 4
properties = []
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('mace').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.quarterstaff]
name = "Quarterstaff"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 2
cost.currency = "sp"
damages = [{dice = "1d6", type = "bludgeoning"}]
weight = 4
properties = ["versatile"]
versatile_damage = "1d8"
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('quarterstaff').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.sickle]
name = "Sickle"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 1
cost.currency = "gp"
damages = [{dice = "1d4", type = "slashing"}]
weight = 2
properties = ["light"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('sickle').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.spear]
name = "Spear"
category = "weapon"
weapon_category = "simple"
weapon_type = "melee"
cost.amount = 1
cost.currency = "gp"
damages = [{dice = "1d6", type = "piercing"}]
weight = 3
properties = ["thrown", "versatile"]
range_normal = 20
range_long = 60
versatile_damage = "1d8"
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('spear').is_proficient * character_trait('proficiency_bonus').bonus"

# Simple Ranged Weapons

[equipment.light_crossbow]
name = "Light Crossbow"
category = "weapon"
weapon_category = "simple"
weapon_type = "ranged"
cost.amount = 25
cost.currency = "gp"
damages = [{dice = "1d8", type = "piercing"}]
weight = 5
properties = ["ammunition", "loading", "two-handed"]
range_normal = 80
range_long = 320
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('dexterity').modifier + equipment('light_crossbow').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.dart]
name = "Dart"
category = "weapon"
weapon_category = "simple"
weapon_type = "ranged"
cost.amount = 5
cost.currency = "cp"
damages = [{dice = "1d4", type = "piercing"}]
weight = 0.25
properties = ["finesse", "thrown"]
range_normal = 20
range_long = 60
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "max(ability('strength').modifier, ability('dexterity').modifier) + equipment('dart').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.shortbow]
name = "Shortbow"
category = "weapon"
weapon_category = "simple"
weapon_type = "ranged"
cost.amount = 25
cost.currency = "gp"
damages = [{dice = "1d6", type = "piercing"}]
weight = 2
properties = ["ammunition", "two-handed"]
range_normal = 80
range_long = 320
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('dexterity').modifier + equipment('shortbow').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.sling]
name = "Sling"
category = "weapon"
weapon_category = "simple"
weapon_type = "ranged"
cost.amount = 1
cost.currency = "sp"
damages = [{dice = "1d4", type = "bludgeoning"}]
properties = ["ammunition"]
range_normal = 30
range_long = 120
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('dexterity').modifier + equipment('sling').is_proficient * character_trait('proficiency_bonus').bonus"

# Martial Melee Weapons

[equipment.battleaxe]
name = "Battleaxe"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 10
cost.currency = "gp"
damages = [{dice = "1d8", type = "slashing"}]
weight = 4
properties = ["versatile"]
versatile_damage = "1d10"
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('battleaxe').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.flail]
name = "Flail"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 10
cost.currency = "gp"
damages = [{dice = "1d8", type = "bludgeoning"}]
weight = 2
properties = []
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('flail').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.glaive]
name = "Glaive"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 20
cost.currency = "gp"
damages = [{dice = "1d10", type = "slashing"}]
weight = 6
properties = ["heavy", "reach", "two-handed"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('glaive').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.greataxe]
name = "Greataxe"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 30
cost.currency = "gp"
damages = [{dice = "1d12", type = "slashing"}]
weight = 7
properties = ["heavy", "two-handed"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('greataxe').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.greatsword]
name = "Greatsword"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 50
cost.currency = "gp"
damages = [{dice = "2d6", type = "slashing"}]
weight = 6
properties = ["heavy", "two-handed"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('greatsword').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.halberd]
name = "Halberd"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 20
cost.currency = "gp"
damages = [{dice = "1d10", type = "slashing"}]
weight = 6
properties = ["heavy", "reach", "two-handed"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('halberd').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.lance]
name = "Lance"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 10
cost.currency = "gp"
damages = [{dice = "1d12", type = "piercing"}]
weight = 6
properties = ["reach", "special"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('lance').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.longsword]
name = "Longsword"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 15
cost.currency = "gp"
damages = [{dice = "1d8", type = "slashing"}]
weight = 3
properties = ["versatile"]
versatile_damage = "1d10"
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('longsword').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.maul]
name = "Maul"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 10
cost.currency = "gp"
damages = [{dice = "2d6", type = "bludgeoning"}]
weight = 10
properties = ["heavy", "two-handed"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('maul').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.morningstar]
name = "Morningstar"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 15
cost.currency = "gp"
damages = [{dice = "1d8", type = "piercing"}]
weight = 4
properties = []
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('morningstar').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.pike]
name = "Pike"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 5
cost.currency = "gp"
damages = [{dice = "1d10", type = "piercing"}]
weight = 18
properties = ["heavy", "reach", "two-handed"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('pike').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.rapier]
name = "Rapier"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 25
cost.currency = "gp"
damages = [{dice = "1d8", type = "piercing"}]
weight = 2
properties = ["finesse"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "max(ability('strength').modifier, ability('dexterity').modifier) + equipment('rapier').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.scimitar]
name = "Scimitar"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 25
cost.currency = "gp"
damages = [{dice = "1d6", type = "slashing"}]
weight = 3
properties = ["finesse", "light"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "max(ability('strength').modifier, ability('dexterity').modifier) + equipment('scimitar').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.shortsword]
name = "Shortsword"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 10
cost.currency = "gp"
damages = [{dice = "1d6", type = "piercing"}]
weight = 2
properties = ["finesse", "light"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "max(ability('strength').modifier, ability('dexterity').modifier) + equipment('shortsword').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.trident]
name = "Trident"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 5
cost.currency = "gp"
damages = [{dice = "1d6", type = "piercing"}]
weight = 4
properties = ["thrown", "versatile"]
range_normal = 20
range_long = 60
versatile_damage = "1d8"
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('trident').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.war_pick]
name = "War Pick"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 5
cost.currency = "gp"
damages = [{dice = "1d8", type = "piercing"}]
weight = 2
properties = []
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('war_pick').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.warhammer]
name = "Warhammer"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 15
cost.currency = "gp"
damages = [{dice = "1d8", type = "bludgeoning"}]
weight = 2
properties = ["versatile"]
versatile_damage = "1d10"
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('strength').modifier + equipment('warhammer').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.whip]
name = "Whip"
category = "weapon"
weapon_category = "martial"
weapon_type = "melee"
cost.amount = 2
cost.currency = "gp"
damages = [{dice = "1d4", type = "slashing"}]
weight = 3
properties = ["finesse", "reach"]
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "max(ability('strength').modifier, ability('dexterity').modifier) + equipment('whip').is_proficient * character_trait('proficiency_bonus').bonus"

# Martial Ranged Weapons

[equipment.blowgun]
name = "Blowgun"
category = "weapon"
weapon_category = "martial"
weapon_type = "ranged"
cost.amount = 10
cost.currency = "gp"
damages = [{dice = "1", type = "piercing"}]
weight = 1
properties = ["ammunition", "loading"]
range_normal = 25
range_long = 100
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('dexterity').modifier + equipment('blowgun').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.hand_crossbow]
name = "Hand Crossbow"
category = "weapon"
weapon_category = "martial"
weapon_type = "ranged"
cost.amount = 75
cost.currency = "gp"
damages = [{dice = "1d6", type = "piercing"}]
weight = 3
properties = ["ammunition", "light", "loading"]
range_normal = 30
range_long = 120
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('dexterity').modifier + equipment('hand_crossbow').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.heavy_crossbow]
name = "Heavy Crossbow"
category = "weapon"
weapon_category = "martial"
weapon_type = "ranged"
cost.amount = 50
cost.currency = "gp"
damages = [{dice = "1d10", type = "piercing"}]
weight = 18
properties = ["ammunition", "heavy", "loading", "two-handed"]
range_normal = 100
range_long = 400
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('dexterity').modifier + equipment('heavy_crossbow').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.longbow]
name = "Longbow"
category = "weapon"
weapon_category = "martial"
weapon_type = "ranged"
cost.amount = 50
cost.currency = "gp"
damages = [{dice = "1d8", type = "piercing"}]
weight = 2
properties = ["ammunition", "heavy", "two-handed"]
range_normal = 150
range_long = 600
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('dexterity').modifier + equipment('longbow').is_proficient * character_trait('proficiency_bonus').bonus"

[equipment.net]
name = "Net"
category = "weapon"
weapon_category = "martial"
weapon_type = "ranged"
cost.amount = 1
cost.currency = "gp"
weight = 3
properties = ["thrown", "special"]
range_normal = 5
range_long = 15
is_proficient.type = "accumulator"
is_proficient.base = "0"
attack_bonus.formula = "ability('dexterity').modifier + equipment('net').is_proficient * character_trait('proficiency_bonus').bonus"
