[character_trait.proficiency_bonus]
name = "Proficiency Bonus"
bonus.type = "accumulator"
bonus.base = "2"

[character_trait.speed]
name = "Speed"
unit = "feet"
amount.type = "accumulator"
amount.base = "0"

[character_trait.darkvision]
name = "Darkvision"
range.type = "accumulator"
range.base = "0"
