[character_trait.experience_points]
name = "Experience Points"
total.type = "accumulator"
total.base = "0"

[character_trait.character_level]
name = "Character Level"
level.type = "mapping"
level.input = "character_trait('experience_points').total"
level.steps = [
  [0, 1],
  [300, 2],
  [900, 3],
  [2700, 4],
  [6500, 5],
  [14000, 6],
  [23000, 7],
  [34000, 8],
  [48000, 9],
  [64000, 10],
  [85000, 11],
  [100000, 12],
  [120000, 13],
  [140000, 14],
  [165000, 15],
  [195000, 16],
  [225000, 17],
  [255000, 18],
  [285000, 19],
  [305000, 20],
]

[character_trait.max_hit_points]
name = "Max Hit Points"
points.type = "accumulator"
points.base = "0"

[character_trait.proficiency_bonus]
name = "Proficiency Bonus"
bonus.type = "accumulator"
bonus.base = "floor((character_trait('character_level').level - 1) / 4) + 2"

[character_trait.speed]
name = "Speed"
unit = "feet"
amount.type = "accumulator"
amount.base = "0"

[character_trait.darkvision]
name = "Darkvision"
range.type = "accumulator"
range.base = "0"

[character_trait.initiative]
name = "Initiative"
bonus.type = "accumulator"
bonus.base = "ability('dexterity').modifier"

[character_trait.passive_perception]
name = "Passive Perception"
score.type = "accumulator"
score.base = "10 + skill('perception').modifier"

[character_trait.armor_class]
name = "Armor Class"
base.type = "accumulator"
base.base = "10"
dex_bonus.type = "accumulator"
dex_bonus.base = "ability('dexterity').modifier"
total.formula = "character_trait('armor_class').base + character_trait('armor_class').dex_bonus"

[character_trait.spellcasting_ability_modifier]
name = "Spellcasting Ability Modifier"
value.type = "accumulator"
value.base = "0"

[character_trait.spell_save_dc]
name = "Spell Save DC"
score.formula = "8 + character_trait('proficiency_bonus').bonus + character_trait('spellcasting_ability_modifier').value"

[character_trait.spell_attack_bonus]
name = "Spell Attack Bonus"
bonus.formula = "character_trait('proficiency_bonus').bonus + character_trait('spellcasting_ability_modifier').value"

[character_trait.full_caster_slots]
name = "Full Caster Spell Slots"
level_1.type = "mapping"
level_1.input = "character_trait('character_level').level"
level_1.steps = [[1, 2], [2, 3], [3, 4]]
level_2.type = "mapping"
level_2.input = "character_trait('character_level').level"
level_2.steps = [[1, 0], [3, 2], [4, 3]]
level_3.type = "mapping"
level_3.input = "character_trait('character_level').level"
level_3.steps = [[1, 0], [5, 2], [6, 3]]
level_4.type = "mapping"
level_4.input = "character_trait('character_level').level"
level_4.steps = [[1, 0], [7, 1], [8, 2], [9, 3]]
level_5.type = "mapping"
level_5.input = "character_trait('character_level').level"
level_5.steps = [[1, 0], [9, 1], [10, 2], [18, 3]]
level_6.type = "mapping"
level_6.input = "character_trait('character_level').level"
level_6.steps = [[1, 0], [11, 1], [19, 2]]
level_7.type = "mapping"
level_7.input = "character_trait('character_level').level"
level_7.steps = [[1, 0], [13, 1], [20, 2]]
level_8.type = "mapping"
level_8.input = "character_trait('character_level').level"
level_8.steps = [[1, 0], [15, 1]]
level_9.type = "mapping"
level_9.input = "character_trait('character_level').level"
level_9.steps = [[1, 0], [17, 1]]

[character_trait.half_caster_slots]
name = "Half Caster Spell Slots"
level_1.type = "mapping"
level_1.input = "character_trait('character_level').level"
level_1.steps = [[1, 0], [2, 2], [3, 3], [5, 4]]
level_2.type = "mapping"
level_2.input = "character_trait('character_level').level"
level_2.steps = [[1, 0], [5, 2], [7, 3]]
level_3.type = "mapping"
level_3.input = "character_trait('character_level').level"
level_3.steps = [[1, 0], [9, 2], [11, 3]]
level_4.type = "mapping"
level_4.input = "character_trait('character_level').level"
level_4.steps = [[1, 0], [13, 1], [15, 2], [17, 3]]
level_5.type = "mapping"
level_5.input = "character_trait('character_level').level"
level_5.steps = [[1, 0], [17, 1], [19, 2]]

[character_trait.spell_slots]
name = "Spell Slots"
level_1.type = "accumulator"
level_1.base = "0"
level_2.type = "accumulator"
level_2.base = "0"
level_3.type = "accumulator"
level_3.base = "0"
level_4.type = "accumulator"
level_4.base = "0"
level_5.type = "accumulator"
level_5.base = "0"
level_6.type = "accumulator"
level_6.base = "0"
level_7.type = "accumulator"
level_7.base = "0"
level_8.type = "accumulator"
level_8.base = "0"
level_9.type = "accumulator"
level_9.base = "0"

[character_trait.pact_magic]
name = "Pact Magic"
slot_count.type = "accumulator"
slot_count.base = "0"
slot_level.type = "accumulator"
slot_level.base = "0"
