[module]
name = "Dungeons and Dragons 5th Edition SRD"
slug = "dnd_5e_srd"
version = "1.0.0"
family = "dungeons_and_dragons"
series = "dungeons_and_dragons_5e"
publisher = "Wizards of the Coast, Inc."

[[concept_type]]
id = "ability"
name = "Ability"

[[concept_type]]
id = "skill"
name = "Skill"

[[concept_type]]
id = "rolling_method"
name = "Rolling Method"

[[concept_type]]
id = "language"
name = "Language"

[[concept_type]]
id = "roll"
name = "Roll"

[[concept_type]]
id = "equipment"
name = "Equipment"

[[concept_type]]
id = "currency"
name = "Currency"

[[concept_type]]
id = "saving_throw"
name = "Saving Throw"

[[concept_type]]
id = "character_trait"
name = "Character Trait"

[[concept_type]]
id = "race"
name = "Race"

[[concept_type]]
id = "background"
name = "Background"

[[concept_type]]
id = "class"
name = "Class"

[[concept_type]]
id = "character_progression"
name = "Character Progression"

[[concept_type]]
id = "award"
name = "Award"

[[concept_type]]
id = "damage_type"
name = "Damage Type"

[[character_list]]
label = "Skill Proficiencies"
metadata_key = "skill_proficiencies"
concept_type = "skill"

[[character_list]]
label = "Languages"
metadata_key = "languages"
concept_type = "language"
choice_concept_type = "language"

[[character_list]]
label = "Weapon Proficiencies"
metadata_key = "weapon_proficiencies"

[[character_list]]
label = "Armor Proficiencies"
metadata_key = "armor_proficiencies"

[[character_list]]
label = "Tool Proficiencies"
metadata_key = "tool_proficiencies"
choice_concept_type = "equipment"

[[character_list]]
label = "Damage Resistances"
metadata_key = "damage_resistances"
concept_type = "damage_type"

[[metadata_contributions]]
from_type = "class"
from_field = "weapon_proficiencies"
to_type = "equipment"
to_field = "is_proficient"
value = 1
label_filters = [
  {label = "Simple Weapons", filter_field = "weapon_category", filter_value = "simple"},
  {label = "Martial Weapons", filter_field = "weapon_category", filter_value = "martial"}
]

[display]
signed_fields = ["modifier", "bonus"]
